package com.rmldemo.guardsquare.uat.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF8D4E2A)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFFDBCA)
val onPrimaryContainerLight = Color(0xFF331100)
val secondaryLight = Color(0xFF845415)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFFDDBB)
val onSecondaryContainerLight = Color(0xFF2B1700)
val tertiaryLight = Color(0xFF6D5E0F)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFF7E388)
val onTertiaryContainerLight = Color(0xFF211B00)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFFF8F6)
val onBackgroundLight = Color(0xFF221A15)
val surfaceLight = Color(0xFFFFF8F6)
val onSurfaceLight = Color(0xFF221A15)
val surfaceVariantLight = Color(0xFFF4DED4)
val onSurfaceVariantLight = Color(0xFF52443D)
val outlineLight = Color(0xFF85746B)
val outlineVariantLight = Color(0xFFD7C2B9)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF382E29)
val inverseOnSurfaceLight = Color(0xFFFFEDE6)
val inversePrimaryLight = Color(0xFFFFB690)